trigger:
  - main
  - feature

pool: default


stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: terraforminitandplan
        displayName: terraform init and plan job
        pool: default
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'Deepak_Service'
            backendAzureRmStorageAccountName: 'deep55stg'
            backendAzureRmContainerName: 'deepcnt'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          displayName: Validate Job
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        - task: TerraformTask@5
          displayName: Plan Job
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'Deepak_Service'


  - stage: scanning
    displayName: scanning
    jobs:
      - job: terraformtfsec
        displayName: tfsec
        pool: default
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/env/dev'

  - stage: deploy
    displayName: deploy
    jobs:
      - job: manualvalidation
        displayName: manaul validation
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'deepakkumar10038@gmail.com'
            approvers: 'deepakkumar10038@gmail.com'


      - job: terraformapply
        displayName: terraform job apply
        dependsOn: manualvalidation
        pool: Default
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'Deepak_Service'
            backendAzureRmStorageAccountName: 'deep55stg'
            backendAzureRmContainerName: 'deepcnt'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          displayName: Apply Job
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'Deepak_Service'

        